# this is an official Python runtime, used as the parent image
FROM python:3.10

RUN mkdir /usr/src/quantkit
WORKDIR /usr/src/quantkit

RUN pip install --upgrade pip

COPY requirements.txt .
COPY jupyter_requirements.txt .

# Skip the Bloomberg dependencies since those need a firewall exception
# and are not required for the backtesting code.
RUN cat requirements.txt | tr -d '\0' | grep "^bloomberg" --invert | xargs -L 1 pip install
RUN pip install --trusted-host pypi.python.org -r jupyter_requirements.txt

# Create a config file and disable the security token.
RUN mkdir ~/.jupyter
RUN touch ~/.jupyter/jupyter_notebook_config.py
RUN echo "c.NotebookApp.token = ''" > ~/.jupyter/jupyter_notebook_config.py

# Expose the port Jupyter notebooks will listen on
EXPOSE 8888
