$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: quantkit_pipeline_sr
compute: azureml:githubcluster

jobs:
  a:
    code: ../../
    command: >-
      python quantkit/code/sustainable/risk_framework.py

    environment: azureml:docker-img-plus-conda-eg2:10
    description: This pipeline job is created from cli  

